# -*- coding: utf-8 -*-
"""multiagente_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNataW-D3CiBDBJlHFTRTd6nEIF20dOj

# Pipeline Multi-Agente para Machine Learning

Este notebook implementa un sistema con 3 agentes:
1. **Agente 1 - Preprocesador**: Normaliza, imputa, escala y codifica datos -> dataset limpio.
2. **Agente 2 - Entrenador**: Aplica validacion, entrena y selecciona el mejor modelo.
3. **Agente 3 - Comunicador**: Genera reporte + responde preguntas via RAG.

---
## 0. Imports y Configuracion
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression, Ridge, Lasso
from sklearn.svm import SVC, SVR
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, \
    mean_squared_error, mean_absolute_error, r2_score
import json, os, re, warnings
warnings.filterwarnings('ignore')

USAR_MISTRAL = False
MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY", "")

if not MISTRAL_API_KEY:
    try:
        from google.colab import userdata
        MISTRAL_API_KEY = userdata.get("multiagentemistral")
    except (ImportError, ValueError):
        pass

if not MISTRAL_API_KEY:
    key = input("API Key de Mistral (Enter para saltar): ").strip()
    if key:
        MISTRAL_API_KEY = key

if MISTRAL_API_KEY:
    USAR_MISTRAL = True
    os.environ["MISTRAL_API_KEY"] = MISTRAL_API_KEY

try:
    from mistralai import Mistral
    client = Mistral(api_key=MISTRAL_API_KEY) if USAR_MISTRAL else None
except ImportError:
    client = None
    if USAR_MISTRAL:
        print("\u26a0 Instala mistralai: pip install mistralai")

"""---
## 1. Carga del Dataset

Subi tu CSV a Colab (menu lateral > icono de carpeta > upload).
"""

from google.colab import files
print("Sube tu archivo CSV:")
uploaded = files.upload()
nombre_csv = list(uploaded.keys())[0]
df = pd.read_csv(nombre_csv)
print(f"\nColumnas disponibles: {list(df.columns)}")
target_col = input("Nombre de la columna objetivo: ").strip()
problem_type = input("Tipo de problema (classification/regression): ").strip().lower()
while problem_type not in ('classification', 'regression'):
    problem_type = input("Debe ser 'classification' o 'regression': ").strip().lower()

print(f"Dataset shape: {df.shape}")
print(f"Tipo de problema: {problem_type}")
df.head()

def convertir_columnas(df):
    df = df.copy()
    def moneda_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).replace("\u20ac", "").replace(",", "").strip()
        if "B" in s: return float(s.replace("B", "")) * 1_000_000_000
        if "M" in s: return float(s.replace("M", "")) * 1_000_000
        if "K" in s: return float(s.replace("K", "")) * 1_000
        try: return float(s)
        except: return np.nan
    def altura_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).replace('"', "").strip()
        m = re.match(r"(\d+)\s*cm", s)
        if m: return float(m.group(1))
        m = re.match(r"(\d+)'\s*(\d+)\"", s)
        if m: return float(m.group(1)) * 30.48 + float(m.group(2)) * 2.54
        try: return float(s)
        except: return np.nan
    def peso_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).lower().strip()
        m = re.search(r"(\d+\.?\d*)\s*(kg|kgs?)", s)
        if m: return float(m.group(1))
        m = re.search(r"(\d+\.?\d*)\s*(lbs?|pounds?)", s)
        if m: return float(m.group(1)) * 0.453592
        m = re.search(r"(\d+\.?\d*)", s)
        if m: return float(m.group(1))
        return np.nan
    cols_moneda = [c for c in df.columns if c in ["Value", "Wage", "Release Clause"]]
    for c in cols_moneda:
        print(f"  Convirtiendo {c}...")
        df[c] = df[c].apply(moneda_a_num)
    if "Height" in df.columns:
        print("  Convirtiendo Height...")
        df["Height"] = df["Height"].apply(altura_a_num)
    if "Weight" in df.columns:
        print("  Convirtiendo Weight...")
        df["Weight"] = df["Weight"].apply(peso_a_num)
    return df

print("\u2022 Columnas antes de conversion:")
print(df.dtypes)
df = convertir_columnas(df)
print("\n\u2022 Columnas despues de conversion:")
print(df.dtypes)
