# -*- coding: utf-8 -*-
"""multiagente_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNataW-D3CiBDBJlHFTRTd6nEIF20dOj

# Pipeline Multi-Agente para Machine Learning

Este notebook implementa un sistema con 3 agentes:
1. **Agente 1 - Preprocesador**: Normaliza, imputa, escala y codifica datos -> dataset limpio.
2. **Agente 2 - Entrenador**: Aplica validacion, entrena y selecciona el mejor modelo.
3. **Agente 3 - Comunicador**: Genera reporte + responde preguntas via RAG.

---
## 0. Imports y Configuracion
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression, Ridge, Lasso
from sklearn.svm import SVC, SVR
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, \
    mean_squared_error, mean_absolute_error, r2_score
import json, os, re, warnings
warnings.filterwarnings('ignore')

USAR_MISTRAL = False
MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY", "")

if not MISTRAL_API_KEY:
    try:
        from google.colab import userdata
        MISTRAL_API_KEY = userdata.get("multiagentemistral")
    except (ImportError, ValueError):
        pass

if not MISTRAL_API_KEY:
    key = input("API Key de Mistral (Enter para saltar): ").strip()
    if key:
        MISTRAL_API_KEY = key

if MISTRAL_API_KEY:
    USAR_MISTRAL = True
    os.environ["MISTRAL_API_KEY"] = MISTRAL_API_KEY

try:
    from mistralai import Mistral
    client = Mistral(api_key=MISTRAL_API_KEY) if USAR_MISTRAL else None
except ImportError:
    client = None
    if USAR_MISTRAL:
        print("\u26a0 Instala mistralai: pip install mistralai")

"""---
## 1. Carga del Dataset

Subi tu CSV a Colab (menu lateral > icono de carpeta > upload).
"""

from google.colab import files
print("Sube tu archivo CSV:")
uploaded = files.upload()
nombre_csv = list(uploaded.keys())[0]
df = pd.read_csv(nombre_csv)
print(f"\nColumnas disponibles: {list(df.columns)}")
target_col = input("Nombre de la columna objetivo: ").strip()
problem_type = input("Tipo de problema (classification/regression): ").strip().lower()
while problem_type not in ('classification', 'regression'):
    problem_type = input("Debe ser 'classification' o 'regression': ").strip().lower()

print(f"Dataset shape: {df.shape}")
print(f"Tipo de problema: {problem_type}")
df.head()

def convertir_columnas(df):
    df = df.copy()
    def moneda_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).replace("\u20ac", "").replace(",", "").strip()
        if "B" in s: return float(s.replace("B", "")) * 1_000_000_000
        if "M" in s: return float(s.replace("M", "")) * 1_000_000
        if "K" in s: return float(s.replace("K", "")) * 1_000
        try: return float(s)
        except: return np.nan
    def altura_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).replace('"', "").strip()
        m = re.match(r"(\d+)\s*cm", s)
        if m: return float(m.group(1))
        m = re.match(r"(\d+)'\s*(\d+)\"", s)
        if m: return float(m.group(1)) * 30.48 + float(m.group(2)) * 2.54
        try: return float(s)
        except: return np.nan
    def peso_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).lower().strip()
        m = re.search(r"(\d+\.?\d*)\s*(kg|kgs?)", s)
        if m: return float(m.group(1))
        m = re.search(r"(\d+\.?\d*)\s*(lbs?|pounds?)", s)
        if m: return float(m.group(1)) * 0.453592
        m = re.search(r"(\d+\.?\d*)", s)
        if m: return float(m.group(1))
        return np.nan
    cols_moneda = [c for c in df.columns if c in ["Value", "Wage", "Release Clause"]]
    for c in cols_moneda:
        print(f"  Convirtiendo {c}...")
        df[c] = df[c].apply(moneda_a_num)
    if "Height" in df.columns:
        print("  Convirtiendo Height...")
        df["Height"] = df["Height"].apply(altura_a_num)
    if "Weight" in df.columns:
        print("  Convirtiendo Weight...")
        df["Weight"] = df["Weight"].apply(peso_a_num)
    return df

print("\u2022 Columnas antes de conversion:")
print(df.dtypes)
df = convertir_columnas(df)
print("\n\u2022 Columnas despues de conversion:")
print(df.dtypes)

"""---
## 2. Agente 1 -- Preprocesador

**Tareas:**
- Normalizar / escalar numericas
- Imputar valores nulos
- Codificar variables categoricas
- Separar features y target
- Devolver `X_train, X_test, y_train, y_test` limpios
"""

class AgentePreprocesador:
    """Agente 1: Normaliza, imputa, escala y codifica."""

    def __init__(self, numeric_strategy='mean', scaler_type='standard'):
        self.numeric_strategy = numeric_strategy
        self.scaler_type = scaler_type
        self.preprocessor = None
        self.numeric_cols = None
        self.categorical_cols = None

    def fit_transform(self, df, target_col, test_size=0.2, random_state=42):
        X = df.drop(columns=[target_col])
        y = df[target_col]

        self.numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
        self.categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()

        print(f"\u2022 Numericas detectadas: {self.numeric_cols}")
        print(f"\u2022 Categoricas detectadas: {self.categorical_cols}")

        numeric_transformer = Pipeline(steps=[
            ('imputer', SimpleImputer(strategy=self.numeric_strategy)),
            ('scaler', StandardScaler() if self.scaler_type == 'standard' else MinMaxScaler())
        ])

        categorical_transformer = Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ])

        transformers = []
        if self.numeric_cols:
            transformers.append(('num', numeric_transformer, self.numeric_cols))
        if self.categorical_cols:
            transformers.append(('cat', categorical_transformer, self.categorical_cols))

        self.preprocessor = ColumnTransformer(transformers, remainder='drop')

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)

        X_train_processed = self.preprocessor.fit_transform(X_train)
        X_test_processed = self.preprocessor.transform(X_test)

        feature_names = []
        if self.numeric_cols:
            feature_names.extend(self.numeric_cols)
        if self.categorical_cols:
            encoder = self.preprocessor.named_transformers_['cat'].named_steps['encoder']
            feature_names.extend(encoder.get_feature_names_out(self.categorical_cols))

        X_train_processed = pd.DataFrame(X_train_processed, columns=feature_names)
        X_test_processed = pd.DataFrame(X_test_processed, columns=feature_names)

        print(f"\u2022 X_train: {X_train_processed.shape}, X_test: {X_test_processed.shape}")
        return X_train_processed, X_test_processed, y_train, y_test, feature_names

    def get_report(self):
        return {
            'numeric_strategy': self.numeric_strategy,
            'scaler': self.scaler_type,
            'num_features': self.numeric_cols,
            'cat_features': self.categorical_cols,
            'dataset_shape': None
        }

    def get_corpus(self, df, target_col):
        rows, cols = df.shape
        nulos = df.isnull().sum().sum()
        text = f"Dataset con {rows} filas y {cols} columnas. "
        text += f"Columna objetivo: {target_col}. "
        text += f"Valores nulos totales: {nulos}. "
        text += f"Variables numericas ({len(self.numeric_cols)}): {', '.join(self.numeric_cols)}. "
        text += f"Variables categoricas ({len(self.categorical_cols)}): {', '.join(self.categorical_cols)}. "
        text += f"Preprocesamiento: imputacion con {self.numeric_strategy}, escalado {self.scaler_type}, codificacion one-hot."
        return text
