# -*- coding: utf-8 -*-
"""multiagente_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNataW-D3CiBDBJlHFTRTd6nEIF20dOj

# Pipeline Multi-Agente para Machine Learning

Este notebook implementa un sistema con 3 agentes:
1. **Agente 1 - Preprocesador**: Normaliza, imputa, escala y codifica datos -> dataset limpio.
2. **Agente 2 - Entrenador**: Aplica validacion, entrena y selecciona el mejor modelo.
3. **Agente 3 - Comunicador**: Genera reporte + responde preguntas via RAG.

---
## 0. Imports y Configuracion
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression, Ridge, Lasso
from sklearn.svm import SVC, SVR
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, \
    mean_squared_error, mean_absolute_error, r2_score
import json, os, re, warnings
warnings.filterwarnings('ignore')

USAR_MISTRAL = False
MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY", "")

if not MISTRAL_API_KEY:
    try:
        from google.colab import userdata
        MISTRAL_API_KEY = userdata.get("multiagentemistral")
    except (ImportError, ValueError):
        pass

if not MISTRAL_API_KEY:
    key = input("API Key de Mistral (Enter para saltar): ").strip()
    if key:
        MISTRAL_API_KEY = key

if MISTRAL_API_KEY:
    USAR_MISTRAL = True
    os.environ["MISTRAL_API_KEY"] = MISTRAL_API_KEY

try:
    from mistralai import Mistral
    client = Mistral(api_key=MISTRAL_API_KEY) if USAR_MISTRAL else None
except ImportError:
    client = None
    if USAR_MISTRAL:
        print("\u26a0 Instala mistralai: pip install mistralai")

"""---
## 1. Carga del Dataset

Subi tu CSV a Colab (menu lateral > icono de carpeta > upload).
"""

from google.colab import files
print("Sube tu archivo CSV:")
uploaded = files.upload()
nombre_csv = list(uploaded.keys())[0]
df = pd.read_csv(nombre_csv)
print(f"\nColumnas disponibles: {list(df.columns)}")
target_col = input("Nombre de la columna objetivo: ").strip()
problem_type = input("Tipo de problema (classification/regression): ").strip().lower()
while problem_type not in ('classification', 'regression'):
    problem_type = input("Debe ser 'classification' o 'regression': ").strip().lower()

print(f"Dataset shape: {df.shape}")
print(f"Tipo de problema: {problem_type}")
df.head()

def convertir_columnas(df):
    df = df.copy()
    def moneda_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).replace("\u20ac", "").replace(",", "").strip()
        if "B" in s: return float(s.replace("B", "")) * 1_000_000_000
        if "M" in s: return float(s.replace("M", "")) * 1_000_000
        if "K" in s: return float(s.replace("K", "")) * 1_000
        try: return float(s)
        except: return np.nan
    def altura_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).replace('"', "").strip()
        m = re.match(r"(\d+)\s*cm", s)
        if m: return float(m.group(1))
        m = re.match(r"(\d+)'\s*(\d+)\"", s)
        if m: return float(m.group(1)) * 30.48 + float(m.group(2)) * 2.54
        try: return float(s)
        except: return np.nan
    def peso_a_num(val):
        if pd.isna(val): return np.nan
        s = str(val).lower().strip()
        m = re.search(r"(\d+\.?\d*)\s*(kg|kgs?)", s)
        if m: return float(m.group(1))
        m = re.search(r"(\d+\.?\d*)\s*(lbs?|pounds?)", s)
        if m: return float(m.group(1)) * 0.453592
        m = re.search(r"(\d+\.?\d*)", s)
        if m: return float(m.group(1))
        return np.nan
    cols_moneda = [c for c in df.columns if c in ["Value", "Wage", "Release Clause"]]
    for c in cols_moneda:
        print(f"  Convirtiendo {c}...")
        df[c] = df[c].apply(moneda_a_num)
    if "Height" in df.columns:
        print("  Convirtiendo Height...")
        df["Height"] = df["Height"].apply(altura_a_num)
    if "Weight" in df.columns:
        print("  Convirtiendo Weight...")
        df["Weight"] = df["Weight"].apply(peso_a_num)
    return df

print("\u2022 Columnas antes de conversion:")
print(df.dtypes)
df = convertir_columnas(df)
print("\n\u2022 Columnas despues de conversion:")
print(df.dtypes)

"""---
## 2. Agente 1 -- Preprocesador

**Tareas:**
- Normalizar / escalar numericas
- Imputar valores nulos
- Codificar variables categoricas
- Separar features y target
- Devolver `X_train, X_test, y_train, y_test` limpios
"""

class AgentePreprocesador:
    """Agente 1: Normaliza, imputa, escala y codifica."""

    def __init__(self, numeric_strategy='mean', scaler_type='standard'):
        self.numeric_strategy = numeric_strategy
        self.scaler_type = scaler_type
        self.preprocessor = None
        self.numeric_cols = None
        self.categorical_cols = None

    def fit_transform(self, df, target_col, test_size=0.2, random_state=42):
        X = df.drop(columns=[target_col])
        y = df[target_col]

        self.numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
        self.categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()

        print(f"\u2022 Numericas detectadas: {self.numeric_cols}")
        print(f"\u2022 Categoricas detectadas: {self.categorical_cols}")

        numeric_transformer = Pipeline(steps=[
            ('imputer', SimpleImputer(strategy=self.numeric_strategy)),
            ('scaler', StandardScaler() if self.scaler_type == 'standard' else MinMaxScaler())
        ])

        categorical_transformer = Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ])

        transformers = []
        if self.numeric_cols:
            transformers.append(('num', numeric_transformer, self.numeric_cols))
        if self.categorical_cols:
            transformers.append(('cat', categorical_transformer, self.categorical_cols))

        self.preprocessor = ColumnTransformer(transformers, remainder='drop')

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)

        X_train_processed = self.preprocessor.fit_transform(X_train)
        X_test_processed = self.preprocessor.transform(X_test)

        feature_names = []
        if self.numeric_cols:
            feature_names.extend(self.numeric_cols)
        if self.categorical_cols:
            encoder = self.preprocessor.named_transformers_['cat'].named_steps['encoder']
            feature_names.extend(encoder.get_feature_names_out(self.categorical_cols))

        X_train_processed = pd.DataFrame(X_train_processed, columns=feature_names)
        X_test_processed = pd.DataFrame(X_test_processed, columns=feature_names)

        print(f"\u2022 X_train: {X_train_processed.shape}, X_test: {X_test_processed.shape}")
        return X_train_processed, X_test_processed, y_train, y_test, feature_names

    def get_report(self):
        return {
            'numeric_strategy': self.numeric_strategy,
            'scaler': self.scaler_type,
            'num_features': self.numeric_cols,
            'cat_features': self.categorical_cols,
            'dataset_shape': None
        }

    def get_corpus(self, df, target_col):
        rows, cols = df.shape
        nulos = df.isnull().sum().sum()
        text = f"Dataset con {rows} filas y {cols} columnas. "
        text += f"Columna objetivo: {target_col}. "
        text += f"Valores nulos totales: {nulos}. "
        text += f"Variables numericas ({len(self.numeric_cols)}): {', '.join(self.numeric_cols)}. "
        text += f"Variables categoricas ({len(self.categorical_cols)}): {', '.join(self.categorical_cols)}. "
        text += f"Preprocesamiento: imputacion con {self.numeric_strategy}, escalado {self.scaler_type}, codificacion one-hot."
        return text

"""---
## 3. Agente 2 -- Entrenador

**Tareas:**
- Validacion cruzada
- Entrenar multiples modelos
- Seleccionar el mejor segun metricas
- Devolver modelo + metricas
"""

class AgenteEntrenador:
    """Agente 2: Valida, entrena y selecciona el mejor modelo."""

    def __init__(self, problem_type='classification', cv_folds=5):
        self.problem_type = problem_type
        self.cv_folds = cv_folds
        self.results = []
        self.best_model = None
        self.best_model_name = None
        self.best_score = None

    def _get_models(self):
        if self.problem_type == 'classification':
            return {
                'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
                'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
                'SVM': SVC(kernel='rbf', probability=True, random_state=42),
            }
        else:
            return {
                'Linear Regression': LinearRegression(),
                'Ridge': Ridge(alpha=1.0, random_state=42),
                'Lasso': Lasso(alpha=0.1, random_state=42),
                'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42),
                'SVR': SVR(kernel='rbf'),
            }

    def _calc_metrics(self, y_true, y_pred):
        metrics = {}
        if self.problem_type == 'classification':
            metrics['accuracy'] = round(accuracy_score(y_true, y_pred), 4)
            metrics['precision'] = round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 4)
            metrics['recall'] = round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 4)
            metrics['f1_score'] = round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 4)
        else:
            metrics['mse'] = round(mean_squared_error(y_true, y_pred), 4)
            metrics['rmse'] = round(np.sqrt(metrics['mse']), 4)
            metrics['mae'] = round(mean_absolute_error(y_true, y_pred), 4)
            metrics['r2'] = round(r2_score(y_true, y_pred), 4)
        return metrics

    def fit(self, X_train, X_test, y_train, y_test):
        models_dict = self._get_models()

        for name, model in models_dict.items():
            print(f"\n\u25b6 Entrenando {name}...")
            try:
                cv_scores = cross_val_score(model, X_train, y_train, cv=self.cv_folds, scoring='accuracy' if self.problem_type == 'classification' else 'r2')
                cv_mean = round(cv_scores.mean(), 4)
                cv_std = round(cv_scores.std(), 4)
            except Exception as e:
                print(f"  CV fallo: {e}")
                cv_mean, cv_std = None, None

            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            metrics = self._calc_metrics(y_test, y_pred)
            metrics['cv_mean'] = cv_mean
            metrics['cv_std'] = cv_std

            self.results.append({'model_name': name, 'metrics': metrics, 'model': model})
            print(f"  CV mean: {cv_mean} | Test metrics: {metrics}")

        self._select_best()
        return self.best_model, self.best_model_name, self.results

    def _select_best(self):
        key = 'f1_score' if self.problem_type == 'classification' else 'r2'
        best = max(self.results, key=lambda r: r['metrics'].get(key, -np.inf))
        self.best_model = best['model']
        self.best_model_name = best['model_name']
        self.best_score = best['metrics'][key]
        print(f"\n{'='*50}")
        print(f"MEJOR MODELO: {self.best_model_name} ({key}={self.best_score})")
        print(f"{'='*50}")

    def get_report(self):
        report = {'problem_type': self.problem_type, 'cv_folds': self.cv_folds, 'results': [], 'best': {}}
        for r in self.results:
            report['results'].append({'model_name': r['model_name'], 'metrics': r['metrics']})
        report['best'] = {'model_name': self.best_model_name, 'score': self.best_score}
        return report

    def get_corpus(self):
        lines = [f"Tipo de problema: {self.problem_type}."]
        lines.append(f"Validacion cruzada: {self.cv_folds} folds.")
        lines.append(f"Modelos evaluados: {len(self.results)}.")
        for r in self.results:
            m = r['metrics']
            metas = ', '.join([f"{k}={v}" for k, v in m.items() if k not in ('cv_mean', 'cv_std')])
            lines.append(f"Modelo {r['model_name']}: {metas}.")
        lines.append(f"Mejor modelo: {self.best_model_name} con score {self.best_score}.")
        return ' '.join(lines)

"""---
## 4. Agente 3 -- Comunicador (RAG)

**Tareas:**
- Construye un corpus con informacion del dataset y resultados
- Genera reporte en lenguaje natural
- Permite hacer preguntas estilo RAG sobre los resultados
"""

class AgenteComunicador:
    """Agente 3: Reporte + RAG. Usa Mistral si esta disponible."""

    def __init__(self, usar_mistral=False, mistral_client=None):
        self.reporte = ""
        self.usar_mistral = usar_mistral
        self.mistral_client = mistral_client
        self.corpus = ""

    def construir_corpus(self, df, target_col, prepro_agent, train_agent):
        parts = ["=== CORPUS DEL PIPELINE DE ML ==="]
        parts.append(prepro_agent.get_corpus(df, target_col))
        parts.append(train_agent.get_corpus())
        parts.append(f"Cantidad de filas en train: {len(train_agent.results[0]['model'].estimators_ if hasattr(train_agent.results[0]['model'], 'estimators_') else []) if train_agent.results else 0}.")
        self.corpus = ' '.join(parts)
        return self.corpus

    def _consulta_mistral(self, pregunta, corpus):
        prompt = f"""
Eres un analista de datos. Responde la pregunta del usuario basandote ESTRICTAMENTE en la siguiente informacion.
Si la respuesta no esta en la info, deci que no tienes datos suficientes.

INFORMACION:
{corpus}

PREGUNTA: {pregunta}
RESPUESTA:"""
        try:
            res = self.mistral_client.chat.complete(
                model="mistral-small-latest",
                messages=[{"role": "user", "content": prompt}]
            )
            return res.choices[0].message.content
        except Exception as e:
            return f"[Error: {e}]"

    def _responder_sin_mistral(self, pregunta, corpus):
        corpus_lower = corpus.lower()
        pq_lower = pregunta.lower()

        if "mejor modelo" in pq_lower or "ganador" in pq_lower:
            idx = corpus.find("Mejor modelo:")
            if idx >= 0:
                return corpus[idx:idx+100].split('.')[0] + '.'
        if "metrica" in pq_lower or "resultado" in pq_lower:
            idx = corpus.find("Modelos evaluados:")
            if idx >= 0:
                return corpus[idx:].split('Mejor')[0].strip() + '.'
        if "variable" in pq_lower or "columna" in pq_lower or "numerica" in pq_lower:
            idx = corpus.find("Variables numericas")
            if idx >= 0:
                end = corpus.find("Preprocesamiento", idx)
                return corpus[idx:end].strip()
        if "nulo" in pq_lower or "falta" in pq_lower:
            idx = corpus.find("Valores nulos")
            if idx >= 0:
                end = corpus.find("Variables", idx)
                return corpus[idx:end].strip()
        return "No tengo suficiente informacion para responder eso."

    def preguntar(self, pregunta):
        if not self.corpus:
            return "Primero ejecuta generar_reporte() para construir el corpus."
        if self.usar_mistral and self.mistral_client:
            return self._consulta_mistral(pregunta, self.corpus)
        else:
            return self._responder_sin_mistral(pregunta, self.corpus)

    def _generar_reporte_mistral(self, prepro_report, train_report, corpus):
        prompt = f"""
Eres un analista de datos. Genera un reporte claro y profesional en espanol.

INFORMACION:
{corpus}

Estructura: 1) Preprocesamiento, 2) Entrenamiento, 3) Resumen Ejecutivo.
"""
        try:
            res = self.mistral_client.chat.complete(
                model="mistral-small-latest",
                messages=[{"role": "user", "content": prompt}]
            )
            return res.choices[0].message.content
        except Exception as e:
            return f"[Error al generar reporte: {e}]"

    def _generar_reporte_template(self, prepro_report, train_report):
        lines = ["=" * 55, "REPORTE FINAL DEL PIPELINE MULTI-AGENTE", "=" * 55]
        num_f = prepro_report['num_features'] or []
        cat_f = prepro_report['cat_features'] or []
        lines.append("\n[Agente 1 - Preprocesador]")
        lines.append("-" * 35)
        lines.append(f"Estrategia de imputacion numerica: {prepro_report['numeric_strategy']}")
        lines.append(f"Tipo de escalado: {prepro_report['scaler']}")
        lines.append(f"Variables numericas ({len(num_f)}): {', '.join(num_f) if num_f else 'ninguna'}")
        lines.append(f"Variables categoricas ({len(cat_f)}): {', '.join(cat_f) if cat_f else 'ninguna'}")
        lines.append("Resultado: Dataset limpio, sin nulos, escalado y codificado.")
        lines.append("\n[Agente 2 - Entrenador]")
        lines.append("-" * 35)
        lines.append(f"Tipo de problema: {train_report['problem_type'].capitalize()}")
        lines.append(f"Validacion cruzada: {train_report['cv_folds']} folds")
        lines.append(f"Modelos evaluados: {len(train_report['results'])}")
        lines.append("")
        lines.append("Resultados por modelo:")
        for r in train_report['results']:
            m = r['metrics']
            metas = ', '.join([f"{k}={v}" for k, v in m.items() if k not in ('cv_mean', 'cv_std')])
            cv = f"CV(mean={m['cv_mean']}, std={m['cv_std']})" if m.get('cv_mean') is not None else "CV: N/A"
            lines.append(f"  - {r['model_name']}: {metas} | {cv}")
        best = train_report['best']
        lines.append(f"\n=> MODELO SELECCIONADO: {best['model_name']} con score {best['score']}")
        lines.append("\n[Resumen Ejecutivo]")
        lines.append("-" * 35)
        var_count = len(num_f) + len(cat_f)
        rec = "usar este modelo en produccion" if best['score'] > 0.8 else "explorar mas modelos o realizar feature engineering"
        lines.append(f"Se procesaron {var_count} variables. El mejor modelo fue {best['model_name']} con rendimiento {best['score']}. Se recomienda {rec}.")
        lines.append("\n" + "=" * 55)
        lines.append("FIN DEL REPORTE")
        lines.append("=" * 55)
        return "\n".join(lines)

    def generar_reporte(self, df, target_col, prepro_agent, train_agent):
        self.construir_corpus(df, target_col, prepro_agent, train_agent)
        prepro_report = prepro_agent.get_report()
        train_report = train_agent.get_report()
        if self.usar_mistral and self.mistral_client:
            self.reporte = self._generar_reporte_mistral(prepro_report, train_report, self.corpus)
        else:
            self.reporte = self._generar_reporte_template(prepro_report, train_report)
        return self.reporte

    def mostrar_reporte(self):
        print(self.reporte)

    def guardar_reporte(self, ruta="reporte_multiagente.txt"):
        with open(ruta, 'w', encoding='utf-8') as f:
            f.write(self.reporte)
        print(f"Reporte guardado en: {ruta}")

"""---
## 5. Ejecucion del Pipeline Multi-Agente
"""

TARGET_COL = target_col
PROBLEM_TYPE = problem_type
TEST_SIZE = 0.2
RANDOM_STATE = 42
CV_FOLDS = 5

print("\u2550" * 50)
print("AGENTE 1: PREPROCESADOR")
print("\u2550" * 50)
agente1 = AgentePreprocesador(numeric_strategy='mean', scaler_type='standard')
X_train, X_test, y_train, y_test, feature_names = agente1.fit_transform(
    df, TARGET_COL, test_size=TEST_SIZE, random_state=RANDOM_STATE
)

print("\n" + "\u2550" * 50)
print("AGENTE 2: ENTRENADOR")
print("\u2550" * 50)
agente2 = AgenteEntrenador(problem_type=PROBLEM_TYPE, cv_folds=CV_FOLDS)
best_model, best_name, all_results = agente2.fit(X_train, X_test, y_train, y_test)

print("\n" + "\u2550" * 50)
print("AGENTE 3: COMUNICADOR")
print("\u2550" * 50)
agente3 = AgenteComunicador(usar_mistral=USAR_MISTRAL, mistral_client=client)
reporte = agente3.generar_reporte(df, TARGET_COL, agente1, agente2)
agente3.mostrar_reporte()
agente3.guardar_reporte("reporte_multiagente.txt")

"""---
## 6. Preguntas al Dataset (RAG)

El Agente 3 construyo un corpus con todos los resultados. Hace preguntas sobre el dataset y los modelos.
"""

preguntas = [
    "Cual fue el mejor modelo y que puntuacion obtuvo?",
    "Que variables numericas y categoricas tiene el dataset?",
    "Como se preprocesaron los datos?",
    "Que tan confiable es el resultado segun las metricas?",
]

for i, p in enumerate(preguntas, 1):
    print(f"\n--- Pregunta {i} ---")
    print(f"P: {p}")
    print(f"R: {agente3.preguntar(p)}")

"""---
## 7. Resultados Finales

Ejecuta las celdas en orden. Podes:
- Cambiar el dataset (CSV, sklearn, etc.)
- Ajustar hiperparametros de cada agente
- Agregar mas modelos en `AgenteEntrenador._get_models()`
- Guardar el modelo entrenado con `joblib.dump(best_model, 'modelo.pkl')`
"""
